version: '3.5'
services:
  sample-api:
    build: .
    image: sample-api
    container_name: sample-api
    hostname: sample-api
    ports:
      - 8080:8080
    networks:
      - development
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=tourist
      - SESSION_REDIS_HOST=redis
      - SESSION_REDIS_PORT=6379
      - SESSION_REDIS_DB=9
      - SESSION_REDIS_SECRET=secret_word
    volumes:
      - ../:/code
      - /code/node_modules
networks:
  development:
    external:
      name: development